export const ReactionType = {
  LIKE: 'like',
  LOVE: 'love',
  LAUGH: 'laugh',
  WOW: 'wow',
  SAD: 'sad',
  ANGRY: 'angry',
  THOUGHTFUL: 'thoughtful',
  CONFUSED: 'confused',
  FLY: 'fly',
  FIRE: 'fire',
  CLAP: 'clap',
  GENIUS: 'genius',
  INSPIRING: 'inspiring',
  MIND_BLOWN: 'mind_blown',
  CURIOUS: 'curious',
  CELEBRATE: 'celebrate',
  THANKS: 'thanks',
  COOL: 'cool',
  SKEPTICAL: 'skeptical',
};
