export const ReactionType = {
  LIKE: 'like',
  DISLIKE: 'dislike',
  LOVE: 'love',
  LAUGH: 'laugh',
  WOW: 'wow',
  SAD: 'sad',
  ANGRY: 'angry',
  THOUGHTFUL: 'thoughtful',
  CONFUSED: 'confused',
  FLY: 'fly',
  FIRE: 'fire',
  CLAP: 'clap',
  GENIUS: 'genius',
  INSPIRING: 'inspiring',
  MIND_BLOWN: 'mind_blown',
  CURIOUS: 'curious',
  CELEBRATE: 'celebrate',
  THANKS: 'thanks',
  COOL: 'cool',
  SKEPTICAL: 'skeptical'
};

export const ReactionEmoji = {
  [ReactionType.LIKE]: '👍',
  [ReactionType.DISLIKE]: '👎',
  [ReactionType.LOVE]: '❤️',
  [ReactionType.LAUGH]: '😂',
  [ReactionType.WOW]: '😮',
  [ReactionType.SAD]: '😢',
  [ReactionType.ANGRY]: '😠',
  [ReactionType.THOUGHTFUL]: '🤔',
  [ReactionType.CONFUSED]: '😕',
  [ReactionType.FLY]: '🪰',
  [ReactionType.FIRE]: '🔥',
  [ReactionType.CLAP]: '👏',
  [ReactionType.GENIUS]: '🧠',
  [ReactionType.INSPIRING]: '💡',
  [ReactionType.MIND_BLOWN]: '🤯',
  [ReactionType.CURIOUS]: '🧐',
  [ReactionType.CELEBRATE]: '🎉',
  [ReactionType.THANKS]: '🙏',
  [ReactionType.COOL]: '😎',
  [ReactionType.SKEPTICAL]: '🤨'
};
